export default {
    words: {
      alltag: ["Car","Cat","Pizza","School","Boss","Coffee","Police","Internet","Garden","Soccer","Train","Hospital","Party","Neighbor","Doctor","Supermarket","Fridge","Bicycle","Mailbox","Carpet","Window","Stairs","Elevator","Doorbell"],
      essen: ["Sushi","Burger","Noodles","Cake","Bread","Cheese","Beer","Wine","Smoothie","Fries","Salad","Steak","Chocolate","Chips","Pineapple","Strawberry","Honey","Jam","Espresso","Watermelon"],
      natur: ["Lightning","Snow","Fog","Storm","Rainbow","Full Moon","Tree","Rose","Mushroom","Butterfly","Eagle","Wolf","Bear","Fox","Lion","Penguin","Cactus","Volcano","Avalanche","Glacier"],
      tech: ["Password","Selfie","Robot","Drone","AI","Podcast","Streaming","Update","Meme","Emoji","Algorithm","Dark Mode","Wi-Fi","Battery","Hologram","Smartwatch","VR Headset","Satellite","Chip","Charging Station"],
      orte: ["Airport","Station","Museum","Library","Bunker","Temple","Palace","Island","Prison","Lighthouse","Market Square","Rooftop Terrace","Parking Garage","Cave","Desert","Jungle","Graveyard","Barracks","Castle","Tower"],
      gefühle: ["Panic","Jealousy","Euphoria","Homesickness","Nightmare","Silence","Curiosity","Dizziness","Goosebumps","Boredom","Longing","Defiance","Shame","Pride","Awe"],
      objekte: ["Suitcase","Compass","Diary","Mirror","Candle","Letter","Mask","Clock","Scissors","Balloon","Boomerang","Lantern","Magic Wand","Binoculars","Snorkel","Magnifying Glass","Dice","Telescope","Box","Key"],
      misc: ["Ghost","Unicorn","Detective","Heroine","Villain","Guru","Captain","Influencer","Therapist","Retiree","Apprentice","Intern","Twin","Legend","Stranger"],
    },
    actions: {
      easy: [
        "Wink","Scratch your nose","Clear your throat","Look briefly at the floor",
        "Stretch","Fix your hair","Tap the table once","Cross your arms",
        "Lean back","Sigh quietly","Bite your lip","Rub your hands",
        "Shrug your shoulders","Snap your fingers","Look at your watch",
        "Nod once","Put a finger to your lips","Stroke your chin",
      ],
      medium: [
        "Laugh out loud","Say: Interesting...","Clap your hands","Say: Oh really?!",
        "Make a surprised face","Half-stand up and sit back down","Tap someone",
        "Pretend to take a photo","Say: Hold on...","Say: No way!",
        "Slap your forehead","Raise your hand like you're in school",
        "Look dramatically to the side","Wiggle in your chair","Point at someone else",
        "Say: I know that and nod wisely","Hum quietly","Look at the ceiling and nod",
      ],
      chaos: [
        "Jump up and shout: EUREKA!","Repeat the last word out loud","Interrupt with: HMM!",
        "Pretend someone kicked you","Make a dramatic pause and stare at everyone",
        "Shout: Bingo! and regret it immediately","Say your name backwards",
        "Put both hands on your cheeks like Kevin","Whisper something unintelligible to your neighbor",
        "Stand up, take one step, and sit back down","Sing one short note",
        "Pretend to grab something from the air","Say: I will only say this... then fall silent",
        "Fake sneeze three times in a row","Write something imaginary in the air",
        "Stare at someone silently for 4 seconds","Give two thumbs up and grin",
      ],
    },
    genres: [
      { id: "alltag", label: "Everyday Life", emoji: "🏠", desc: "Supermarket, office, neighborhood" },
      { id: "urlaub", label: "Vacation", emoji: "✈️", desc: "Beach, hotel, adventure" },
      { id: "party", label: "Party", emoji: "🎉", desc: "Celebration, friends, chaos" },
      { id: "arbeit", label: "Work", emoji: "💼", desc: "Meeting, boss, cafeteria" },
      { id: "natur", label: "Nature", emoji: "🌲", desc: "Forest, animals, adventure" },
      { id: "zukunft", label: "Future", emoji: "🚀", desc: "AI, robots, space travel" },
      { id: "krimi", label: "Mystery", emoji: "🔍", desc: "Detective, suspicion, suspense" },
      { id: "random", label: "Random", emoji: "🎲", desc: "Completely unexpected" },
    ],
    diffLabels: { easy: "😇 Easy", medium: "😏 Medium", chaos: "😈 Chaos", mix: "🎲 Mix" },
    categoryLabels: { alltag: "🏠 Everyday", essen: "🍕 Food", natur: "🌲 Nature", tech: "🤖 Tech", orte: "🏛 Places", gefühle: "💫 Feelings", objekte: "🎩 Objects", misc: "👤 Characters" },
    aiSystem: "Creative storyteller in English.",
    aiPrompt: (genre, words, minChars, targetChars) => `Write a funny story in English in the style "${genre}". The story must be at least ${minChars} characters long and should ideally land around ${targetChars} characters. Use ALL of these words: ${words.join(", ")}. Every target word must appear at least twice. The repeated occurrences of a word should usually appear in different sentences, not directly in the same sentence. Mark every target word occurrence with **word**. Return ONLY the story, with no title, no list, and no explanation. Keep it lively and fun to read aloud.`,
  };
